version: "3"

services:
  percona:
    image: percona
    environment:
     - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
     - "3306:3306"

# mysql:
#   build: ./mysql/
#   image: mysql-docker
#   environment:
#     - MYSQL_ROOT_PASSWORD=root
#   volumes:
#     - ./data:/var/lib/mysql
#   ports:
#     - "3306:3306"
