version: '3.8'

services:
 node:
  build:
   context: ./node
   target: prod
  ports:
   - 8080:8080
  environment:
   - SERVER_PORT=8080

 test:
  build:
   context: ./node
   target: test
  ports:
   - 8080:8080
  environment:
   - SERVER_PORT=8080
