version: "3"

services:
  backend:
    build: ./backend/
    image: aspnetcore_6.1
    volumes:
      - backend-storage:/app:rw
    env_file:
      - .env
    ports:
      - "5000:80"
      
  nginx:
    build: ./mysql/
    image: mysql-docker
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3306:3306"