
version: "3"

services:
  percona:
    image: percona
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    ports:
      - "3306:3306"

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=Password123
    ports:
      - "5432:5432"